### ISSUE TITLE
Question about compiling

### ISSUE THREAD

**Issue by bicarbonate** [itzg/haproxy-gen#1]
So I know nothing about Go, but I do need an HAP config generator so I'm wanting to try this one. And I'm just unable to tell what to do to compile this.  Any chance for some advice or maybe just make fun of me?  I can't even click on the Wiki button so IDK if there's content in there or not. But I'm really wanting to try this out.
Thanks~!

**Comment by bicarbonate** [comment]
Im a dullard. Sorry, ignore me :)

**Comment by itzg** [comment]
Phew 😀 , I haven't touched this code in almost 3 years and have long since switched away from glide dependency management.
